spring.application.name=ECI

server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.root=INFO
logging.level.cloudSecurityLocal.ECI=DEBUG

# Security
spring.security.user.name=admin
# spring.security.user.password set via environment variable

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
